apiVersion: ec2.aws.upbound.io/v1beta1
kind: xxx
metadata:
 name: xxx
spec:
  refs:
    - toFieldPath: spec.forProvider.vpcEndpointId
      valueFrom:
        referableRef:
          name: referable-networkfirewall-endpoints
          key: value[0].syncStates[1].attachment[0].endpointId
          optional: false
    - toFieldPath: spec.forProvider.vpcEndpointId
      valueFrom:
        secretKeyRef:
          name: referable-networkfirewall-endpoints
          namespace: namespace-a
          key: attribute.key
          optional: false
    - toFieldPath: spec.forProvider.vpcEndpointId
      valueFrom:
        configmapKeyRef:
          name: referable-networkfirewall-endpoints
          namespace: namespace-b
          key: attribute.key
          optional: false
